update

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -30,6 +30,16 @@ jobs:
     - name: Login to Amazon ECR
       uses: aws-actions/amazon-ecr-login@v2
 
+    - name: Create ECR Repository if not exists
+        run: |
+          REPO_NAME=${{ secrets.ECR_REPOSITORY }}
+          if ! aws ecr describe-repositories --repository-names "$REPO_NAME" 2>/dev/null; then
+            echo "Repository $REPO_NAME not found. Creating..."
+            aws ecr create-repository --repository-name "$REPO_NAME"
+          else
+            echo "Repository $REPO_NAME already exists."
+          fi
+
     - name: Set Image Version to Build Number
       run: echo "IMAGE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV
 
